{{- if .Values.index_gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.indexGatewayFullname" . }}
  labels:
    {{- include "loki.indexGatewayLabels" . | nindent 4 }}
    {{- with .Values.index_gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "loki.indexGatewaySelectorLabels" . | nindent 4 }}
{{- end }}
