{{- if .Values.agent.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "otel-collector.agentFullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector.agentLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.agent.annotations | nindent 4 }}
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      {{- include "otel-collector.agentSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-collector.agentLabels" . | nindent 8 }}
        {{- with .Values.agent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include "otel-collector.agentConfigChecksum" . }}
        {{- if .Values.agent.podAnnotations }}
        {{- include "ContentRender" ( dict "value" .Values.agent.podAnnotations "context" . ) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.agent.serviceAccount.name | default (include "otel-collector.serviceAccountName" . ) }}
      {{- if .Values.agent.priorityClassName }}
      priorityClassName: {{ .Values.agent.priorityClassName }}
      {{- end }}
      {{- if .Values.agent.securityContext.enabled }}
      securityContext: {{- omit .Values.agent.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.agent.hostNetwork }}
      hostNetwork: true
      {{- end }}
      tolerations:
        {{- toYaml .Values.agent.tolerations | nindent 8 }}
      initContainers:
        {{- toYaml .Values.agent.initContainers | nindent 8 }}
      containers:
        - name: agent
          {{- include "Image" .Values.global.image.otelCollector | nindent 10 }}
          command:
            - /otelcol-contrib
          args:
            - --config=/etc/opentelemetry/agent.yaml
          volumeMounts:
            {{- if .Values.agent.extraVolumeMounts }}
            {{- toYaml .Values.agent.extraVolumeMounts | nindent 12}}
            {{- end }}
            - mountPath: /etc/opentelemetry
              name: {{ template "otel-collector.agentFullname" . }}-config
          ports:
            {{- include "otel-collector.agentContainerListenPort" . | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.agent.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.agent.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.agent.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          {{- if .Values.agent.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.agent.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            {{- if .Values.agent.env }}
              {{- toYaml .Values.agent.env | nindent 12 }}
            {{- end }}
          {{- with .Values.agent.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.agent.extraContainers }}
        {{- toYaml .Values.agent.extraContainers | nindent 8}}
        {{- end }}
      volumes:
        {{- include "otel-collector.agentConfigVolume" . | nindent 8 }}
        {{- if .Values.agent.extraVolumes }}
        {{- toYaml .Values.agent.extraVolumes | nindent 8}}
        {{- end }}
{{- end -}}