apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.agentFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent.agentLabels" . | nindent 4 }}
    {{- with .Values.agent.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.agent.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- include "agent.agentServiceListenPort" . | nindent 4 }}
  selector:
    {{- include "agent.agentSelectorLabels" . | nindent 4 }}
