config:
  exporters:
    metric: 
      endpoint: "http://gateway-nginx-nginx.infrastore.svc.cluster.local:8889/api/prom/push"
      tls:
        insecure: true
        insecure_skip_verify: true
    log:
      endpoint: http://gateway-nginx-nginx.infrastore.svc.cluster.local:8888/api/prom/push
      format: json
      labels:
        resource:
          k8s.namespace.name: "namespace"
          k8s.pod.name: "pod_name"
          k8s.container.name: "container_name"
          stream: "stream"
    trace: 
      endpoint: gateway-nginx-nginx.infrastore.svc.cluster.local:8891
      tls:
        insecure: true
        insecure_skip_verify: true
      headers:
        x-scope-orgid: 1

agent:
  enabled: true
  hostNetwork: false
  extraVolumes: 
    - name: zoneinfo
      hostPath:
        path: /etc/localtime
    - name: varlog
      hostPath:
        path: /var/log
      #containers
    - name: docker
      hostPath:
        path: /var/lib/docker/containers
        # path: /var/lib/docker
  extraVolumeMounts: 
    - name: zoneinfo
      mountPath: /etc/localtime
      readOnly: true
    - name: varlog
      mountPath: /var/log
    - name: docker
      #containers
      # mountPath: /var/lib/docker
      mountPath: /var/lib/docker/containers
      readOnly: true
collector:
  enabled: false