{{- if and (gt (int .Values.ingester.replicas) 1) (.Values.ingester.podDisruptionBudget) (.Values.ingester.enabled) }}
apiVersion: {{ include "tempo.pdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.ingesterFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.ingesterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.ingesterSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.ingester.podDisruptionBudget | nindent 2 }}
{{- end }}
