{{- if and (gt (int .Values.instance.replicas) 1) (.Values.instance.podDisruptionBudget) }}
apiVersion: {{ include "PdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "cortex.instanceFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.instanceLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.instanceSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.instance.podDisruptionBudget | nindent 2 }}
{{- end }}
