apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stack-ingress
  namespace: infrastore
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.mason
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: grafana-grafana
                port:
                  number: 3000
          - pathType: Prefix
            path: /api/live
            backend:
              service:
                name: grafana-grafana
                port:
                  number: 3000