{{- if and (gt (int .Values.query_scheduler.replicas) 1) (.Values.query_scheduler.podDisruptionBudget) (.Values.query_scheduler.enabled) }}
apiVersion: {{ include "PdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "mimir.querySchedulerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.querySchedulerLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mimir.querySchedulerSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.query_scheduler.podDisruptionBudget | nindent 2 }}
{{- end }}
