apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}-memberlist
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.config.memberlist.bindPort }}
      protocol: TCP
      name: gossip
      targetPort: gossip
  selector:
    {{- include "mimir.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist