{{- if .Values.store_gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.storeGatewayFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.storeGatewayLabels" . | nindent 4 }}
    {{- with .Values.store_gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.store_gateway.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.config.server.grpcListenPort }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "mimir.storeGatewaySelectorLabels" . | nindent 4 }}
{{- end -}}
