{{- if and (gt (int .Values.querier.replicas) 1) (.Values.querier.podDisruptionBudget) (.Values.querier.enabled) }}
apiVersion: {{ include "PdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "mimir.querierFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.querierLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mimir.querierSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.querier.podDisruptionBudget | nindent 2 }}
{{- end }}
