apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.writeFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.writeLabels" . | nindent 4 }}
    {{- with .Values.write.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.write.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.httpListenPort }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "mimir.writeSelectorLabels" . | nindent 4 }}
