{{- if and (gt (int .Values.write.replicas) 1) (.Values.write.podDisruptionBudget) }}
apiVersion: {{ include "cortex.pdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "cortex.writeFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.writeLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cortex.writeSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.write.podDisruptionBudget | nindent 2 }}
{{- end }}
