{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent.operatorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent.operatorLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operator.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "agent.operatorSelectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.operator.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "agent.operatorLabels" . | nindent 8 }}
        {{- with .Values.operator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.operator.podAnnotations }}
      annotations:
        {{- include "ContentRender" ( dict "value" .Values.operator.podAnnotations "context" . ) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.operator.serviceAccount.name | default (include "agent.serviceAccountName" . ) }}
      {{- if .Values.operator.priorityClassName }}
      priorityClassName: {{ .Values.operator.priorityClassName }}
      {{- end }}
      {{- if .Values.operator.securityContext.enabled }}
      securityContext: {{- omit .Values.operator.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- toYaml .Values.operator.initContainers | nindent 8 }}
      containers:
        - name: operator
          {{- include "Image" .Values.global.image.agent_operator | nindent 10 }}
          {{- if or (and .Values.config.kubeletService.namespace .Values.config.kubeletService.serviceName) (.Values.extraArgs) }}
          args:
            {{- if and .Values.config.kubeletService.namespace .Values.config.kubeletService.serviceName }}
            - --kubelet-service={{ .Values.config.kubeletService.namespace }}/{{ .Values.config.kubeletService.serviceName }}
            {{- end }}
            {{- if .Values.extraArgs  }}
            {{- range .Values.extraArgs  }}
            - {{ . }}
            {{- end }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          {{- if .Values.operator.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.operator.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
        {{- if .Values.operator.extraContainers }}
        {{- toYaml .Values.operator.extraContainers | nindent 8}}
        {{- end }}
{{- end }}