apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.port }}
      protocol: TCP
      name: server
      targetPort: server
  selector:
    {{- include "memcached.selectorLabels" . | nindent 4 }}
