{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.config.server.metricPort }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "memcached.selectorLabels" . | nindent 4 }}
{{- end }}