apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "caddy.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
data:
  Caddyfile: |-
    {
      admin 0.0.0.0:2019
    }
    :8080 {
        respond /live 200
        respond /ready 200
    }
    import /etc/caddy/blocks/*.caddy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "caddy.fullname" . }}-config-blocks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
data:
  {{- if .Values.config.serverBlocks }}
  {{- range $key, $val := .Values.config.serverBlocks }}
  {{ $key }}.caddy: |-
    {{- include "ContentRender" ( dict "value" $val "context" $ ) | nindent 4 }}
  {{ end -}}
  {{- end }}
