apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  server-blocks-paths.conf: |-
    include  "/opt/bitnami/nginx/conf/server_blocks/ldap/*.conf";
    include  "/opt/bitnami/nginx/conf/server_blocks/common/*.conf";
  server-block.conf: |-
    {{- include "ContentRender" ( dict "value" .Values.config.serverBlock "context" . ) | nindent 4 }}

