{{- if and (gt (int .Values.ruler.replicas) 1) (.Values.ruler.podDisruptionBudget) }}
apiVersion: {{ include "PdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "mimir.rulerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.rulerLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mimir.rulerSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.ruler.podDisruptionBudget | nindent 2 }}
{{- end }}
