apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "alertmanager.fullname" . }}-clusterrolebinding
  labels:
  {{- include "alertmanager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "alertmanager.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ template "alertmanager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
