apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.readFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.readLabels" . | nindent 4 }}
    {{- with .Values.read.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.read.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.httpListenPort }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "loki.readSelectorLabels" . | nindent 4 }}
