apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.readFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.readSelectorLabels" . | nindent 4 }}
    {{- with .Values.read.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.read.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.config.server.grpcListenPort }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "loki.readSelectorLabels" . | nindent 4 }}
