apiVersion: v1
kind: Service
metadata:
  name: {{ include "synthetic.agentFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic.agentLabels" . | nindent 4 }}
    {{- with .Values.agent.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.agent.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4050
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "synthetic.agentSelectorLabels" . | nindent 4 }}
