{{- if and (gt (int .Values.agent.replicas) 1) (.Values.agent.podDisruptionBudget) }}
apiVersion: {{ include "PdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "synthetic.agentFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic.agentLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "synthetic.agentSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.agent.podDisruptionBudget | nindent 2 }}
{{- end }}
