apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "alertmanager.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
data:
  alertmanager.yaml: |-
    auth_enabled: true
    api:
      response_compression_enabled: true
    server:
      http_listen_port: {{ .Values.config.server.httpListenPort }}
      grpc_listen_port: {{ .Values.config.server.grpcListenPort }}
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 100000
    memberlist:
      bind_port: {{ .Values.config.memberlist.bindPort }}
      # -- the service name of the memberlist
      # if using memberlist discovery
      join_members:
        - {{ include "alertmanager.fullname" . }}-memberlist.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.config.memberlist.bindPort }}
      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s
      gossip_to_dead_nodes_time: 1h
    alertmanager:
      data_dir: /data
      enable_api: true
      external_url: /alertmanager
      sharding_enabled: true
      sharding_ring:
        kvstore:
          store: memberlist
          prefix: alertmanager/
    alertmanager_storage:
      {{- if .Values.config.storage.backend }}
      backend: {{.Values.config.storage.backend}}
      {{- if eq .Values.config.storage.backend "gcs"}}
      gcs:
        {{- toYaml .Values.config.storage.gcs | nindent 4}}
      {{- end }}
      {{- if eq .Values.config.storage.backend "s3"}}
      s3:
        {{- toYaml .Values.config.storage.s3 | nindent 4}}
      {{- end }}
      {{- if eq .Values.config.storage.backend "azure"}}
      azure:
        {{- toYaml .Values.config.storage.azure | nindent 4}}
      {{- end }}
      {{- if eq .Values.config.storage.backend "swift"}}
      swift:
        {{- toYaml .Values.config.storage.swift | nindent 4}}
      {{- end }}
      {{- else if .Values.minio.enabled }}
      backend: s3
      s3:
        endpoint: {{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:9000
        {{- with (index .Values.minio.buckets 0) }}
        bucket_name: {{ .name }}
        {{- end }}
        access_key_id: {{ .Values.minio.accessKey }}
        secret_access_key: {{ .Values.minio.secretKey }}
        insecure: true
        http:
          insecure_skip_verify: true
      {{- else }}
      backend: filesystem
      filesystem:
        dir: /data/rules
      {{- end }}
    
  runtime_config.yaml: |-
    overrides: {}