{{- if .Values.distributor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.distributorFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.distributorLabels" . | nindent 4 }}
    {{- with .Values.distributor.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.distributor.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.config.server.grpcListenPort }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    {{- include "tempo.distributorSelectorLabels" . | nindent 4 }}
{{- end }}