{{- if .Values.compactor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.compactorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.compactorLabels" . | nindent 4 }}
    {{- with .Values.compactor.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.compactor.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.httpListenPort }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "mimir.compactorSelectorLabels" . | nindent 4 }}
{{- end -}}
