apiVersion: v1
kind: Service
metadata:
  name: {{ include "tns.dbFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tns.dbLabels" . | nindent 4 }}
    {{- with .Values.db.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.db.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "tns.dbSelectorLabels" . | nindent 4 }}
