apiVersion: v2
name: cortex
description: Horizontally scalable, highly available, multi-tenant, long term Prometheus.
version: 0.1.0
appVersion: 1.16.0
home: https://cortexmetrics.io/
kubeVersion: ^1.19.0-0
dependencies:
  - name: memcached
    alias: memcached-frontend
    version: 0.1.0
    repository: http://localhost:8080/
    condition: memcached-frontend.enabled
  - name: memcached
    alias: memcached-blocks-index
    version: 0.1.0
    repository: http://localhost:8080/
    condition: memcached-blocks-index.enabled
  - name: memcached
    alias: memcached-blocks-chunk
    version: 0.1.0
    repository: http://localhost:8080/
    condition: memcached-blocks-chunk.enabled
  - name: memcached
    alias: memcached-blocks-metadata
    version: 0.1.0
    repository: http://localhost:8080/
    condition: memcached-blocks-metadata.enabled
  - name: minio
    alias: minio
    version: 8.0.9
    repository: https://helm.min.io/
    condition: minio.enabled