{{- if .Values.querier.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.querierFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.querierLabels" . | nindent 4 }}
    {{- with .Values.querier.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.querier.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.httpListenPort }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "loki.querierSelectorLabels" . | nindent 4 }}
{{- end -}}