apiVersion: v1
kind: Service
metadata:
  name: {{ include "ksm.ksmFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksm.ksmLabels" . | nindent 4 }}
    {{- with .Values.ksm.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.ksm.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:  
  - name: https-main
    port: 8443
    targetPort: https-main
  - name: https-self
    port: 9443
    targetPort: https-self
  selector:
    {{- include "ksm.ksmSelectorLabels" . | nindent 4 }}
