apiVersion: v1
kind: Secret
metadata:
  name: {{ template "synthetic.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic.labels" . | nindent 4 }}
strinData:
  api-token: {{- include "ContentRender" ( dict "value" .Values.config.token "context" . ) }}
type: Opaque
  

