{{- if .Values.collector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.collectorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector.collectorLabels" . | nindent 4 }}
    {{- with .Values.collector.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.collector.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- include "otel-collector.collectorServiceListenPort" . | nindent 4 }}
  selector:
    {{- include "otel-collector.collectorSelectorLabels" . | nindent 4 }}
{{- end -}}
