{{- if and (gt (int .Values.query_scheduler.replicas) 1) (.Values.query_scheduler.podDisruptionBudget) (.Values.query_scheduler.enabled) }}
apiVersion: {{ include "loki.pdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.querySchedulerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.querySchedulerLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.querySchedulerSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.query_scheduler.podDisruptionBudget | nindent 2 }}
{{- end }}
