apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.nginxFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx.nginxLabels" . | nindent 4 }}
    {{- with .Values.nginx.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.nginx.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.httpListenPort }}
      protocol: TCP
      name: http
      targetPort: http
  selector:
    {{- include "nginx.nginxSelectorLabels" . | nindent 4 }}
