{{- if .Values.eventhandler.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.eventhandlerFullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent.eventhandlerLabels" . | nindent 4 }}
data:
  agent.yml: |-
    server:
      log_level: info
      http_listen_port: {{ .Values.config.server.httpListenPort }}
    {{- if .Values.config.logs.clients }}
    logs:
      configs:
        - clients:
            {{- include "ContentRender" ( dict "value" .Values.config.logs.clients "context" . ) | nindent 12 }}
          name: default
          scrape_configs:
            - job_name: eventhandler_logs
              kubernetes_sd_configs:
                - role: pod
              pipeline_stages:
                - docker: {}
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: __host__
                - action: keep
                  regex: {{ include "agent.eventhandlerFullname" . }}-*
                  source_labels:
                    - __meta_kubernetes_pod_name
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - action: replace
                  replacement: $1
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: job
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                - replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
          positions:
            filename: /data/positions.yaml
    {{- end }}
    integrations:
      eventhandler:
        cache_path: "/data/eventhandler.cache"
{{- end }}