{{- if and (gt (int .Values.distributor.replicas) 1) (.Values.distributor.podDisruptionBudget) (.Values.distributor.enabled) }}
apiVersion: {{ include "PdbVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.distributorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.distributorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.distributorSelectorLabels" . | nindent 6 }}
  {{- toYaml .Values.distributor.podDisruptionBudget | nindent 2 }}
{{- end }}
