{{- if .Values.distributor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.distributorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.distributorLabels" . | nindent 4 }}
    {{- with .Values.distributor.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.distributor.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.httpListenPort }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "loki.distributorSelectorLabels" . | nindent 4 }}
{{- end }}